//! Wire-stable tokens for the owner-epoch fence, and the classifier over them.
//!
//! **The producer moved.** `MetadataState::ensure_owner_epoch` — the only thing
//! that emits these messages — now lives in `crates/manager/src/store.rs`,
//! because the manager's in-memory state has to be able to hold records only
//! the manager may name. The tokens and the matcher stayed here so that
//! `autumn-stream` can classify a manager rejection without depending on the
//! manager crate.
//!
//! The old comment here said the matcher was "kept ADJACENT to the ONLY
//! producer so the message shapes and this matcher can only evolve together".
//! Adjacency was never what did that work, and it is worth saying plainly now
//! that it is gone: the two share the `OWNER_*_TOKEN` constants below, so a
//! reword cannot detach the matcher, and `owner_fence_matcher_pairs_with_producer`
//! (in the manager crate, beside the producer) classifies errors generated by
//! the REAL producer rather than by literals. Both mechanisms are intact.

/// Wire-stable tokens SHARED by the producer
/// (`autumn_manager::store::MetadataState::ensure_owner_epoch`) and the
/// classifier (`is_owner_epoch_fence_message` below). Single source
/// of truth: a reword of the rejection message cannot detach the matcher —
/// both sides reference the same consts, and the manager crate's
/// `owner_fence_matcher_pairs_with_producer` test (which classifies errors
/// generated by the REAL producer, not literals) backstops any refactor
/// that stops using them. Renaming/removing a token is a WIRE-visible
/// change for mixed-version clusters (old client matching new manager
/// text): treat it like a wire-schema edit — same-commit stop-world only.
pub const OWNER_KEY_PREFIX_TOKEN: &str = "owner_key=";
pub const OWNER_EPOCH_MISMATCH_TOKEN: &str = "owner_epoch mismatch";
pub const OWNER_KEY_MISSING_TOKEN: &str = "does not exist";

/// Classifier for `ensure_owner_epoch` rejection messages. The producer lives
/// in the manager crate (see this module's header); the pairing is held by the
/// shared tokens above plus the `owner_fence_matcher_pairs_with_producer` test
/// there, which runs this matcher over errors the real producer made.
///
/// Why a message matcher at all: over the wire an owner-epoch fence is just
/// `CODE_PRECONDITION`, indistinguishable from ordinary preconditions
/// ("stream cannot be empty after punch holes", admin-token checks, …)
/// without a new wire code — and a new code in `manager_rpc.rs` changes
/// a stop-world WIRE version bump (see `WIRE_VERSION`). The
/// stream-layer `StreamClient` uses this to turn a manager-side fence into
/// the "LockedByOther" classification that drives the PS's
/// poison-and-reopen self-heal (reopen re-acquires a fresh owner_epoch),
/// mirroring what the extent-node layer already signals natively via
/// `CODE_LOCKED_BY_OTHER`.
pub fn is_owner_epoch_fence_message(msg: &str) -> bool {
    msg.contains(OWNER_EPOCH_MISMATCH_TOKEN)
        || (msg.contains(OWNER_KEY_PREFIX_TOKEN) && msg.contains(OWNER_KEY_MISSING_TOKEN))
}

